### ISSUE TITLE
How does Placeholder work?

### ISSUE THREAD

**Issue by izanev** [HemantNegi/jquery.sumoselect#112]
Hello,

Something is unclear to me (v2.1.0)

In documentation, it's stated that placeholder would first be searched (by order of priority) in "placeholder" attribute. Then, it goes to the first selected option that's not disabled. And then, at last it tries the passed "placeholder" option.

Well, in my case I want to show a placeholder, different from default option and I was trying to use the placeholder attribute as it should be having the highest priority.

It doesn't.

In the code I see that highest priority is the default, selected option.

Can you let me know how to show a placeholder via the placeholder attribute and not the default option?

**Comment by HemantNegi** [comment]
Documentation is a bit incorrect, actually its valid for multiselect.
But due to the behavior of normal select element its not possible to impose to placeholder functionality.
so the only way around is to have a `selected` `disabled`  options.

read this thread : http://stackoverflow.com/questions/9447134/html-select-how-to-set-default-text-which-wont-be-shown-in-drop-down-list
