### ISSUE TITLE
On mobile view, multi select not working

### ISSUE THREAD

**Issue by talhavbase** [HemantNegi/jquery.sumoselect#133]
Thanks for good work in sumoselect
It have issue in mobile view for multi-select . It can be observed in given demo 
http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html

It also have compatibility issue with Materializecss.

**Comment by HemantNegi** [comment]
Can you please elaborate more about issue
Thanks

**Comment by talhavbase** [comment]
'Multiple select' is not working on mobiles screens
Please observe it by opening above link (' Simple' section) on mobile screen

**Comment by HemantNegi** [comment]
What device are you trying on

**Comment by Jklick** [comment]
Seeing same issue on iphone and samsung galaxy. Clicking 'ok' for multi-select in mobile isn't actually selecting the filters and sending through a call to adjust results. Is this something that can be resolved quickly?

**Comment by FieryStudios** [comment]
I'm seeing this same issue on my iPhone 5. Specifically, what I see is that the "Floating" version of the menu is being overridden by the iPhone's default dropdown behavior.  I get the typical iPhone select interface instead of the floating menu, and because our specific application is relying on the OK/CANCEL MulitiControls buttons, there's no way for us to submit the form, since they never appear.

Here's how we're invoking the code -- please note that the floating version of the menu is set to take over at 640px wide, and I'm seeing the error on a 320w iPhone 5 in portrait mode: 

$selectBoxes.SumoSelect(
		{
			csvDispCount: 1,
			captionFormat: '{0} selected',
			floatWidth: 640,
			okCancelInMulti: true,
			triggerChangeCombined : false,
			selectAll : false
		}
	);

Thanks for your attention to this! We're excited to be using this plugin and we hope we can find a solution because our client really loves it.

**Comment by Jklick** [comment]
Update: Our issue turned out not to be a bug afterall. We did not set forceCustomRendering: true.  Thanks!

**Comment by Avalesh** [comment]
Sumo-select multiple is not working on mobile, please check and resolve.

**Comment by Jklick** [comment]
What is this?  Chris, do you know?

Julie Klick   P.M.P.
Project Manager
261 E Kalamazoo Ave, Suite 300; Kalamazoo, MI 49007
office: +1. 269.342.7544
fax: +1.269.382.4558
email: jklick@vml.com<mailto:jklick@vml.com>

**Comment by Talhamansoor** [comment]
use triggerChangeCombined:false

**Comment by mkhreportsdev** [comment]
It is still not working for multi-select on some resolutions.
If the select box is multi-select then it is not working on resolutions like 1024X786, 1280X786, etc.
Please check your demo link
[http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html](http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html)
Open the window in any of the above-mentioned resolutions and reload the page
You can see the problem for multi-select

**Comment by calrrox** [comment]
> It is still not working for multi-select on some resolutions. If the select box is multi-select then it is not working on resolutions like 1024X786, 1280X786, etc. Please check your demo link http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html Open the window in any of the above-mentioned resolutions and reload the page You can see the problem for multi-select

Hi @mkhreportsdev, try adding `forceCustomRendering: true` to initial options values. That works for me.

**Comment by PraveenChordia** [comment]
try adding `forceCustomRendering: true` to the initial options values.
Also make sure that the `floatWidth:` parameter is less than your screen width, for it to work properly.
I set it to 0 so it works for all screen sizes.
