### ISSUE TITLE
Multi Select: On "Select All", UI do not respond for long time if I have many select options(>150).

### ISSUE THREAD

**Issue by susheelvit** [HemantNegi/jquery.sumoselect#150]
I am using multi select and my UI does not respond when I have many select options (like > 150 options) and UI un-response time increases if my select options increases.

For example, I have 3000 options and when I click "Select All" my UI do not respond for 10-15 seconds.

Browser: Chrome
Browser: FF throws unresponsive warning pop-up multiple times.

**Comment by wubzz** [comment]
Have the same issue, especially problematic when re-rendering large dropdowns. The culprit as far as I can tell is probably: https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js#L594

For each iteration the function will tell jquery to select "the current iteration" from the DOM two times and also "lookup" the index, for no reason, since the argument `el` and `ix` is already there. A dropdown with 1000 options would then equal to 2000 jquery `$.find` and 2000 `$.index` calls, and this load is not counting what happens next in the iteration.

**Comment by OvernetData** [comment]
@wubzz I found that made little difference. A number of changes are necessary to get any significant improvement:

1. in onOptClick(), move the li.click handler code out to a separate function:

                onOptClick: function (li) {
                    var O = this;
                    li.click(function (event) {
                        event.stopImmediatePropagation();
                        O.itemClicked($(this));
                    });
                },

2. In SelAll(), instead of triggering a click on each item call your new itemClicked() function, passing the item, so instead of 
if(!e.hasClass('selected'))e.trigger('click');
you have
if(!e.hasClass('selected')) O.itemClicked(e);

Changes 1 and 2 cut the time in half - I don't know why the click event is taking so long to fire, or why it randomly varies, but (at least in Chrome) it does.

3. In the new itemClicked() function I think there's a bit of incorrect logic on the decision to call setText() and callChange() - where it reads:
if (!(O.is_multi && settings.triggerChangeCombined && (O.is_floating || settings.okCancelInMulti))) {
I think it should be:
if ((!O.is_multi && !settings.triggerChangeCombined && !(O.is_floating || settings.okCancelInMulti))) {
...this further reduces the processing time to much more reasonable levels.

Prior to these changes select all was simply not fit for purpose on any list of more than about 10 items, now hundreds are OK.

**Comment by pikilipita** [comment]
Will be fix be added soon to the master releases? I'm facing the same performances issues...

**Comment by HemantNegi** [comment]
@OvernetData Can you raise a Pull Request with these changes

**Comment by amarsalunke** [comment]
Hi Hemant ,I am using multi select and my UI does not respond when I have many select options (like > 500 options) and UI un-response time increases if my select options increases.
For example, I have 5000 options and when I click "Select All" my UI do not respond for 20 seconds. 
I also do updated changes wubuzz refering..Please give me any solution

**Comment by bdas900** [comment]
Hi hemant, I am using multi select drop down with ajax reload. multiselect having 1300 checkbox, when i select select all checkbox it will take much more time.please give me solution.
