### ISSUE TITLE
.blur() function not firing

### ISSUE THREAD

**Issue by shanafme** [HemantNegi/jquery.sumoselect#154]
I'm trying to do some validation checking after a user selects a series of options in a SumoSelect Multiselect box.  I would prefer to wait until after the user has selected all of the options and moved focus off of the control rather than checking at each .change() event.  Is this possible with SumoSelect?  I am trying to use .blur(), but it never seems to fire from the sumoSelect box.

Please see this JSFiddle:
https://jsfiddle.net/ey4mnb1y/1/

I have an alert kick off at both .change() and .blur(), but the .blur() never runs...

**Comment by dhanendra-kumar** [comment]
Hi @shanafme
In case to use blur you have to bind blur event with the parent div of select box because on UI you are not focus on select box, focus is on the <p> and <div class="optWrapper">.

You can handle it by using - 

$("#island1").parent().blur(function() {
  alert('island1 blur');
});

It will work in your case. Hope this help :)
