### ISSUE TITLE
Search don't work with accent

### ISSUE THREAD

**Issue by diegomachado1** [HemantNegi/jquery.sumoselect#160]
If I have an option called 'Maçã' the search should work if someone write 'maça' or 'maca'.
Is possible to fix this?

**Comment by HemantNegi** [comment]
see this line https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js#L253
it uses indexOf() to match a substring. That should work with any character set.
but `ç` can not be equal to `e` , so that will not be possible (or we need to implement a more localized matching function).
Also check the page encoding and make sure it is "unicode" (UTF-8 likely).

**Comment by diegomachado1** [comment]
Ok, I solved the problem but I have not time to fork and commit for now, but I'll do this soon.
