### ISSUE TITLE
Leveraging NoMatch to Add New item to the collection

### ISSUE THREAD

**Issue by jorgecas99** [HemantNegi/jquery.sumoselect#275]
I make it like this

`$(".SlectBoxSearchAdd").SumoSelect({
    search: true,
    noMatch: "No matches for \"{0}\" <a class=\"newSumo\">Add new</a>"
});
`

and then

`$(".SumoSelect").on("click", ".newSumo", function(){
newopt = $(this).parents(".SumoSelect").find(".search-txt").val();
var sumoFind = $(this).parents(".SumoSelect").find("select");
sumoFind[0].sumo.add(newopt);
sumoFind[0].sumo.unSelectAll();
sumoFind[0].sumo.selectItem(newopt);
sumoFind[0].sumo.reload();
});
`

This works fine

_Originally posted by @cakama3a in https://github.com/HemantNegi/jquery.sumoselect/issues/123#issuecomment-216164475_

**Comment by jorgecas99** [comment]
When using this method and piggy riding on the No Match option, works once and doesn't work after that. I thought it was the "Add New" event losing bind but that is no the case. I think is something with the 'no match' method that is forcing it to run once. Any ideas?

**Comment by Zenoo** [comment]
This is caused by the `.reload()` call.  

https://github.com/HemantNegi/jquery.sumoselect/blob/048729a1b88893c164359c15eec1e62474cf3579/src/jquery.sumoselect.js#L692-L695

The element is regenerated, which makes you loose your listener.  
Attaching the listener to a parent node should solve your issue.
