### ISSUE TITLE
Partial Select All Behavior: Allow Optional Configuration?

### ISSUE THREAD

**Issue by kieran-ojakangas** [HemantNegi/jquery.sumoselect#319]
My team is wondering if it is possible to update the script to allow the select all partial display behavior to NOT appear on the page.

What I mean is - instead of having the "dithered/disabled" checkbox at the top of the dropdown when some items are selected, we'd like to just have the checkbox ONLY appear to be unchecked UNTIL all items are selected as we've been seeing in previous script versions.

Previous desired behavior:

![image](https://user-images.githubusercontent.com/94488305/148095574-48c9de89-1f5d-4134-8ae0-1387e63e5789.png)

New (undesired) behavior:

![image](https://user-images.githubusercontent.com/94488305/148095774-a733c27c-152e-4611-9b6e-84e0702fda8a.png)

**Comment by Zenoo** [comment]
There was 2 things here.  
First of all, there was a bug preventing the checkbox to actualize correctly, which has now been fixed in v3.4.0.  
Please check if the default configuration is what you wanted.  

If not, I introduced the option `selectAllPartialCheck`, which, when set to `false`, shows an empty checkbox on partial selects, instead of a disabled one.

Please upgrade your version to [v3.4.0](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.4.0)

**Comment by kieran-ojakangas** [comment]
@Zenoo thank you, that was QUICK. I've tested this and definitely see that it works, and the partial check option is absolutely useful to us. Thank you so much!
